### ISSUE TITLE
Product Service

### ISSUE THREAD

**Issue by sunnybeta** [sunnybeta/rainforest#2]
## Tasks

- [ ] Create the **Product Service** in Go.
- [ ] Merchant can create, update and delete products
- [ ] Setup Elastic Search and insert sample products
